name: GaRiDa
description: '가리다'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=3.2.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    get: ^4.6.6
    sqflite: ^2.3.0
    path: ^1.8.3
    path_provider: ^2.1.1
    image_picker: ^1.0.4
    dio: ^5.3.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - images/Logo_null.png
    fonts:
        - family: NanumSquareNeo
          fonts:
              - asset: font/NanumSquareNeo-aLt.ttf
                weight: 400
              - asset: font/NanumSquareNeo-bRg.ttf
                weight: 400
              - asset: font/NanumSquareNeo-cBd.ttf
                weight: 400
              - asset: font/NanumSquareNeo-dEb.ttf
                weight: 400
              - asset: font/NanumSquareNeo-eHv.ttf
                weight: 400
